apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-deployment
  namespace: roboshop
  labels:
   project: roboshop
   component: shipping
   tier: backend
spec:
  minReplicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: shipping
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        component: shipping
        tier: backend
    spec:
      containers:
        - name: shipping-container
          image: joindevops/shipping:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: shipping-config
          ports:
            - name: liveness-port
              port: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 155
          livenessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-svc
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: shipping
    tier: backend
  ports:
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping-hpa
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
