apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: test-ns
  labels:
    app: webapp
spec:
  containers:
    - name: sample-app
      image: codingrefined/chatapp:latest
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: dev-ns
  labels:
    app: webapp
spec:
  containers:
    - name: cont1
      image: codingrefined/chatapp:latest
      ports:
        - containerPort: 3000
