apiVersion: v1
kind: Pod
metadata:
  name: second-app
  namespace: test-ns
  labels:
    app: app2
spec:
  containers:
    - name: micro-app
      image: chaitanyavamsi/micro-api:latest
      ports:
        - containerPort: 5000