apiVersion: v1
kind: Service
metadata:
  name: samplesvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 80           # service Port
      targetPort: 3000   # pod container Port
      nodePort: 30333    # optional nodeport
