apiVersion: v1
kind: ReplicationController
metadata:
  name: mulitpod-rc
  namespace: test-ns
spec:
  replicas: 2
  selector:
    app: webapp
  template:
    metadata:
      name: samplercmultipod
      labels:
        app: webapp
    spec:
      containers:
        - name: cont1
          image: codingrefined/chatapp:latest
          ports:
            - containerPort: 3000
          resources:                   # use when disk pressure or ephemeral-storage errors
            requests:
              ephemeral-storage: "100Mi"
            limits:
              ephemeral-storage: "200Mi"
        - name: cont2
          image: nginx
          ports:
            - containerPort: 80
          resources:                  # use when disk pressure or ephemeral-storage errors
            requests:
              ephemeral-storage: "100Mi"
            limits:
              ephemeral-storage: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: samplesvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 81
      targetPort: 3000
      nodePort: 30334
      name: chatapp
    - port: 80
      targetPort: 80
      nodePort: 30333
      name: nginxapp



# to delete - kubectl delete rc mulitpod-rc -n test-ns