apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sample-daemonset     #controllerName should be alwasy lowercase
  namespace: dev-ns
spec:                 # we do not have replicas
  selector:           # difference is in selectors
    matchLabels:
     app: webapp
  template:
    metadata:
      name: samplepod
      labels:
        app: webapp
    spec:
      containers:
        - name: cont1
          image: nginx
          ports:
            - containerPort: 80
          resources:                  # use when disk pressure or ephemeral-storage errors
            requests:
              ephemeral-storage: "100Mi"
            limits:
              ephemeral-storage: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: replicasvc
  namespace: dev-ns
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30444
      name: nginxapp


# To delete DaemonSet:
# kubectl delete daemonset sample-daemonset -n dev-ns
# will create a pod in every node except in master or cnotrol plane due to tains and tolerations
