apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rolling
  namespace: test-ns
spec:
  replicas: 2
  revisionHistoryLimit: 5
  minReadySeconds: 30        # it will wait 30 seconds until it deletes old pod , for new pod to get ready
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1                # how many new pods will be created
      maxUnavailable: 1          # during update only one pod will be down
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: nginx-app
      labels:
        app: webapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rolling-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30777
     name: nginx-application
