apiVersion: v1
kind:  ReplicationController # deplrecated use replicaSet
metadata:
  name: nginx-rc
  namespace: test-ns
spec:
  replicas: 2
  selector:
    app: nginx-app
  template:
    metadata:
      name: pod-nginx
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - port: 80
      targetPort: 80
