apiVersion: v1
kind: Deployment
metadata:
  name: spring-deployment
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      name: spring-pod
      labels:
        app: spring-app
    containers:
      - name: spring-container
        image: dockerhandson/spring-boot-mongo
        ports:
          - containerPort: 8080 # informational only , telling that app is running on this port
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongo-svc
        - name: MONGO_DB_USERNAME
          value: sampleuser
        - name: MONGO_DB_PASSWORD
          value: sampleuser
---
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    spring-app
  ports:
    - port: 80          # Port exposed by the Service
      targetPort: 8080  # must match container port,Port on container receiving traffic
---
# These ENV variables are MongoDB built-in variables.
# They are used only for:
# Creating the initial root user in MongoDB
# Setting authentication on startup

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo-RS
  namespace: test-ns
spec:
  selector:
    matchLabels:
      db: mongo-db
  template:
    metadata:
      name: mongodb-pod
      labels:
        db: mongo-db
    spec:
      containers:
        - name: mongodb-container
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: sampleuser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: sampleuser
          volumeMounts:
            - name: mongo-vol     # must match with volumes.name
              mountPath: /data/db
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: pvClaim-hostpath
