apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongoapp
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: mongoapp
  template:
    metadata:
      labels:
        app: mongoapp
    spec:
      containers:
        - name: mongocontainer
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: sampleuser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: sampleuser
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: test-ns
spec:
  type: ClusterIP
  selector:
    app: mongoapp
  ports:
    - port: 27017
      targetPort: 27017
