# spring app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: sampleapplication
      labels:
        app: webapp
    spec:
      containers:
        - name: java-container
          image: mithuntechnologies/springboot-mongo-application:1
          ports:
            - containerPort: 8080
          resources:
            requests:
             cpu: "200m"       # Reserve 0.1 CPU where m is millicore
             memory: "256Mi"   # Reserve 64 MiB RAM where MI mebibyte 64Mi = 64 mebibytes = ~67 MB
            limits:
             cpu: "500m"       # Maximum 0.1 CPU
             memory: "500Mi"   # Maximum 256 MiB RAM
          env:
            - name: MONGO_DB_HOSTNAME
              value: mongosvc
            - name: MONGO_DB_USERNAME
              value: sampleuser
            - name: MONGO_DB_PASSWORD
              value: sampleuser
---
# spring Service
apiVersion: v1
kind: Service
metadata:
  name: springsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 8080
---
# mongo app
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongoapp
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: mongoapp
  template:
    metadata:
      labels:
        app: mongoapp
    spec:
      containers:
        - name: mongocontainer
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: sampleuser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: sampleuser
          volumeMounts:
            - name: mongodb-host
              mountPath: /data/db
      volumes: #volumes here new tag
        - name: mongodb-host
          hostPath:
            path: /tmp/dbbackup
---
# mongo Service
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: test-ns
spec:
  type: ClusterIP
  selector:
    app: mongoapp
  ports:
    - port: 27017
      targetPort: 27017
