apiVersion: v1
kind: PersistentVolume
metadata: # can be in any namespace
  name: pv-hostpath
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/mongodata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvClaim-hostpath
  namespace: test-ns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo-RS
  namespace: test-ns
spec:
  selector:
    matchLabels:
      db: mongo-db
  template:
    metadata:
      name: mongodb-pod
      labels:
        db: mongo-db
    spec:
      containers:
        - name: mongodb-container
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: sampleuser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: sampleuser
          volumeMounts:
            - name: mongo-vol     # must match with volumes.name
              mountPath: /data/db
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: pvClaim-hostpath
