apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: rabbitmq
    tier: db
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless-svc
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: rabbitmq
    tier: db
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-statefulset
  namespace: roboshop
spec:
  serviceName: rabbitmq-headless-svc
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      component: rabbitmq
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: db
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq:3
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: roboshop
            - name: RABBITMQ_DEFAULT_PASS
              value: roboshop123
          volumeMounts:
            - name: rabbitmq-pvc
              mountPath: /var/lib/rabbitmq
      volumeClaimTemplates:
        - metadata:
            name: rabbitmq-pvc
          spec:
            storageClassName: "roboshop-ebs-sc"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi
