# service, headless service, statefulset, pvc

apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: roboshop
spec:
  selector:
   project: roboshop
   component: redis
   tier: db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless-svc
  namespace: roboshop
spec:
  clusterIP: None
  selector:
   project: roboshop
   component: redis
   tier: db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
spec:
  serviceName: redis-headless-svc
  selector:
    matchLabels:
      project: roboshop
      component: redis
      tier: db
  replicas: 2
  template:
    metadata:
      labels:
       project: roboshop
       component: redis
       tier: db
    spec:
      containers:
        - name: redis-container
          image: redis:7.0
          volumeMounts:
            - name: redis-pvc
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "roboshop-ebs-sc"
        resources:
          requests:
            storage: 1Gi
