apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: roboshop-ebs-sc # all should be lower case
reclaimPolicy: Retain
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer


# install drivers