apiVersion: v1
kind: Pod
metadata:
 name: nginxapp #pod name
 labels:
    app: nginx
spec:
 containers:
  - name: nginxconatiner #container name
    image: nginx
    ports:
     - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
 name: nginx-svc
 namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
