apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: dev-ns
  labels:
    app: multi-app
spec:
  containers:
    - name: app1 #name mandatory since multiple cont , single container name not mandatory
      image: chaitanyavamsi/micro-api:latest
      ports:
       - containerPort: 5000
    - name: app2
      image: nginx
      ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: multi-svc
  namespace: dev-ns
spec:
  type: NodePort
  selector:
    app: multi-app
  ports:
   - port: 80
     targetPort: 5000
     name: nodeapp
   - port: 81
     targetPort: 80
     name: nginx-app
