apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      name: ds-pod-nginx
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app
          image: nginx
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: test-ns
  name: ds-svc
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30222
