apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-example
  namespace: test-ns
spec:
  replicas: 3 # this wont consider , it follows hpa relicas
  selector:
    matchLabels:
      name: hpa-pod
  template:
    metadata:
      labels:
        name: hpa-pod
    spec:
      containers:
        - name: hpa-container
          image: k8s.gcr.io/hpa-example
          ports: # this is like meta data
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    name: hpa-pod
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: horizontal-auto-scalar-example
  namespace: test-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-example
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 40